name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Clones repo
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/Blog.API

      - name: Build
        run: dotnet build src/Blog.API --no-restore

      - name: Test
        run: dotnet test tests/Blog.Tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Render
        run: curl -s "${{ secrets.RENDER_DEPLOY_HOOK }}"
